### ISSUE TITLE
cors.io is down 

### ISSUE THREAD

**Issue by LabLayers** [gr2m/cors.io#1]
As of 7/30/14 12pm, cors.io is down. http://www.downforeveryoneorjustme.com/cors.io

![screen shot 2014-07-30 at 12 02 12 pm](https://cloud.githubusercontent.com/assets/607807/3751888/e8668f6c-1802-11e4-9996-a7de0582702a.png)

**Comment by jatindhankhar** [comment]
+1

**Comment by gr2m** [comment]
you use it worng. You don't call cors.io directly, you use it as proxy, e.g. using jQuery

```js
$.get('http://cors.io/original-domain.com/path/to.json')
```

**Comment by sb8244** [comment]
`OPTIONS http://cors.io/spreadsheets.google.com/feeds/worksheets/1vtFRMKlzUbj61VTyOPusge52Q_R5JlwlyBKGwbl0oA8/private/full net::ERR_NAME_NOT_RESOLVED`

Am I missing something here @gr2m? cors.io can't be resolved.

**Comment by gr2m** [comment]
I think google does not allow to use http:// requests. Try 
`https://cors-io.herokuapp.com/` instead of `http://cors.io` as the proxy
